#!/bin/bash

serve() {
    python -m http.server 8082
}

push() {
    git fetch origin
    git fetch web
    git push origin main
    git checkout www.nilleb.co
    git pull origin www.nilleb.co
    git merge main
    git push origin www.nilleb.co
    git checkout www.nilleb.com
    git pull web www.nilleb.com
    git merge main
    git push web www.nilleb.com
    git checkout main
}

setup() {
    uv venv
    source .venv/bin/activate
    uv pip install feedgen pytz
}

case "$1" in
    serve)
        serve
        ;;
    push)
        push
        ;;
    rss)
        . .venv/bin/activate
        python3 generate_rss.py
        ;;
    setup)
        setup
        ;;
    *)
        echo "Error: Invalid command. Available commands: serve, push, rss, setup"
        ;;
esac
