#!/bin/bash

setup() {
    uv venv
    . .venv/bin/activate
    uv pip install -r requirements.txt
}

compile() {
    . .venv/bin/activate
    uv pip compile requirements.in > requirements.txt
}

devsync() {
    . .venv/bin/activate
    uv pip sync requirements.txt
}

serve() {
    python -m http.server 8082
}

push() {
    git fetch origin
    git fetch web
    git push origin main
    git checkout www.nilleb.co
    git pull origin www.nilleb.co
    git merge main
    git push origin www.nilleb.co
    git checkout www.nilleb.com
    git pull web www.nilleb.com
    git merge main
    git push web www.nilleb.com
    git checkout main
}

setup() {
    uv sync
}

tweet() {
    . .venv/bin/activate
    uv run python create_bsky_post.py ${@}
}

case "$1" in
    setup)
        setup
        ;;
    devcompile)
        compile
        ;;
    serve)
        serve
        ;;
    devsync)
        devsync
        ;;
    push)
        push
        ;;
    rss)
        . .venv/bin/activate
        python3 generate_rss.py
        ;;
    tweet)
        tweet ${@:2}
        ;;
    setup)
        setup
        ;;
    *)
        echo "Error: Invalid command. Available commands: serve, push, rss, setup"
        ;;
esac
